export type Partner = {
  name: string;
  website?: string;
  linkedin?: string;
  description: string;
  logo?: string;
};

export const partners: Partner[] = [
  {
    name: "Heicoders Academy",
    description: "Practical tech and AI training academy for students and professionals.",
    website: "",
    linkedin: "https://www.linkedin.com/company/heicoders-academy",
    logo: "/partners/heicoders-academy.jpg",
  },
  {
    name: "ManusAI",
    description: "AI-focused organization building tools and experiences for modern workflows.",
    website: "",
    linkedin: "https://www.linkedin.com/company/manus-im/posts/?feedView=all",
    logo: "/partners/manusai.jpg",
  },
  {
    name: "Lytehouse",
    description: "Technology and innovation partner supporting applied AI learning.",
    website: "",
    linkedin: "https://www.linkedin.com/company/lytehouse-ai-sg/",
    logo: "/partners/lytehouse.jpg",
  },
  {
    name: "Workato",
    description: "Enterprise automation platform connecting apps, systems, and AI workflows.",
    website: "",
    linkedin: "https://www.linkedin.com/company/workato",
    logo: "/partners/workato.jpg",
  },
  {
    name: "Chat and Build",
    description: "Builder-first community focused on fast prototyping with AI.",
    website: "",
    linkedin: "https://www.linkedin.com/company/chatandbuild/",
    logo: "/partners/chat-and-build.jpg",
  },
  {
    name: "Lorong AI",
    description: "Community platform driving AI conversations, events, and ecosystem growth.",
    website: "",
    linkedin: "https://www.linkedin.com/company/lorong-ai",
    logo: "/partners/lorong-ai.jpg",
  },
  {
    name: "Singapore AI Safety Hub",
    description: "Initiative advancing responsible AI and AI safety capabilities in Singapore.",
    website: "",
    linkedin: "https://www.linkedin.com/company/singapore-ai-safety-hub/",
    logo: "/partners/singapore-ai-safety-hub.jpg",
  },
  {
    name: "AWS",
    description: "Global cloud platform enabling scalable AI, data, and application development.",
    website: "",
    linkedin: "https://www.linkedin.com/company/amazon-web-services",
    logo: "/partners/aws.jpg",
  },
  {
    name: "Addlly AI",
    description: "AI company supporting productivity and content workflows.",
    website: "",
    linkedin: "https://www.linkedin.com/company/addllyai/",
    logo: "/partners/addlly-ai.jpg",
  },
  {
    name: "Agnes AI",
    description: "AI partner supporting modern product experiences and applied AI initiatives.",
    website: "",
    linkedin: "https://www.linkedin.com/company/agnesaisapiens/posts/?feedView=all",
    logo: "/partners/agnes-ai.jpg",
  },
  {
    name: "Alibaba Cloud",
    description: "Cloud infrastructure and AI platform partner supporting scalable digital innovation.",
    website: "",
    linkedin: "https://www.linkedin.com/company/alibaba-cloud-computing-company",
    logo: "/partners/alibaba-cloud.jpg",
  },
  {
    name: "Puffer AI",
    description: "AI startup exploring practical products and intelligent systems.",
    website: "",
    linkedin: "https://www.linkedin.com/company/puffer-pte-ltd/posts/?feedView=all",
    logo: "/partners/puffer-ai.jpg",
  },
  {
    name: "AI Singapore",
    description: "National AI programme developing talent, research, and industry adoption.",
    website: "",
    linkedin: "https://www.linkedin.com/company/aisingapore/",
    logo: "/partners/ai-singapore.jpg",
  },
  {
    name: "GMI Cloud AI",
    description: "Cloud and AI infrastructure partner supporting experimentation, deployment, and scale.",
    website: "",
    linkedin: "https://www.linkedin.com/company/gmi-cloud-ai/",
    logo: "/partners/gmi-cloud-ai.jpg",
  },
  {
    name: "NVIDIA",
    description: "Computing platform partner powering AI development, training, and accelerated workloads.",
    website: "",
    linkedin: "https://www.linkedin.com/company/nvidia",
    logo: "/partners/nvidia.jpg",
  },
  {
    name: "OpenClawSG",
    description: "Community partner focused on collaborative AI building and practical experimentation.",
    website: "",
    linkedin: "https://www.linkedin.com/company/clawsingapore/",
    logo: "/partners/openclawsg.jpg",
  },
  {
    name: "EY",
    description: "Global professional services firm driving AI and digital transformation projects.",
    website: "",
    linkedin: "https://www.linkedin.com/company/ernstandyoung",
    logo: "/partners/ey.jpg",
  },
  {
    name: "Qwen",
    description: "Foundation model ecosystem partner supporting modern AI application development.",
    website: "",
    linkedin: "https://www.linkedin.com/company/qwen/posts/?feedView=all",
    logo: "/partners/qwen.jpg",
  },
  {
    name: "SGInnovate",
    description: "Deep-tech ecosystem builder investing in and supporting frontier startups.",
    website: "",
    linkedin: "https://www.linkedin.com/company/sginnovate",
    logo: "/partners/sginnovate.jpg",
  },
  {
    name: "Singtel",
    description: "Technology partner supporting digital product and AI innovation efforts.",
    website: "",
    linkedin: "https://www.linkedin.com/company/singtel",
    logo: "/partners/singtel.jpg",
  },
  {
    name: "FinGenesis",
    description: "Fintech-focused organization working at the intersection of finance and technology.",
    website: "",
    linkedin: "https://www.linkedin.com/company/fingenesis/",
    logo: "/partners/fingenesis.jpg",
  },
  {
    name: "Asia AI Association",
    description: "Regional network supporting AI education, collaboration, and thought leadership.",
    website: "",
    linkedin: "https://www.linkedin.com/company/asia-ai-association/",
    logo: "/partners/asia-ai-association.jpg",
  },
  {
    name: "Vinova",
    description: "Product engineering and digital solutions company with AI capabilities.",
    website: "",
    linkedin: "https://www.linkedin.com/company/vinova",
    logo: "/partners/vinova.jpg",
  },
  {
    name: "Pantherpulse",
    description: "AI community and creative-tech platform exploring emerging AI applications.",
    website: "",
    linkedin: "https://www.linkedin.com/company/pantherpulse/",
    logo: "/partners/pantherpulse.jpg",
  },
  {
    name: "Singapore Youth AI",
    description: "AI ecosystem partner supporting community growth, learning, and builder collaboration.",
    website: "",
    linkedin: "https://www.linkedin.com/company/sgyouthai/",
    logo: "/partners/syai.jpg",
  },
  {
    name: "Tencent Cloud",
    description: "Cloud and AI platform partner supporting scalable infrastructure and developer innovation.",
    website: "",
    linkedin: "https://www.linkedin.com/company/tencent-cloud",
    logo: "/partners/tencent-cloud.jpg",
  },
];
